# Generated by Django 4.0.6 on 2023-12-21 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias_juegos',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(choices=[('shooter', 'Shooters'), ('rpg', 'RPG'), ('sports', 'Deportes'), ('action', 'Accion'), ('simulation', 'Simulacion'), ('VR', 'Realidad Virtual'), ('arcade', 'Arcades')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='contacta_nos',
            fields=[
                ('contact_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(default='Ingresa tu nombre', max_length=100)),
                ('contact_mail', models.CharField(default='Ingresa tu correo', max_length=100)),
                ('contact_question', models.TextField(default='Ingresa tu consulta')),
            ],
        ),
        migrations.CreateModel(
            name='posteos_usuarios',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(default='Titulo del articulo', max_length=50)),
                ('post_subtitle', models.CharField(default='Descripcion corta del articulo', max_length=100)),
                ('post_description', models.TextField(default='Ingresa la descripcion larga del articulo')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post-images')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_active', models.BooleanField(default=True)),
                ('post_author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
                ('post_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel_principal.categorias_juegos')),
            ],
            options={
                'ordering': ('-post_date',),
            },
        ),
        migrations.CreateModel(
            name='comentarios_usuarios',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField(default='Ingresa tu comentario')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_image', models.ImageField(blank=True, null=True, upload_to='comment-images')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('comment_related_post', models.ForeignKey(default='Sin comentarios', null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel_principal.posteos_usuarios')),
            ],
        ),
    ]
