# Generated by Django 4.0.6 on 2023-12-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias_juegos',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(choices=[('shooter', 'Shooters'), ('rpg', 'RPG'), ('sports', 'Deportes'), ('action', 'Accion'), ('simulation', 'Simulacion'), ('VR', 'Realidad Virtual'), ('arcade', 'Arcades')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='contacta_nos',
            fields=[
                ('contact_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_mail', models.CharField(max_length=100)),
                ('contact_question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='posteos_usuarios',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_author', models.CharField(max_length=50)),
                ('post_title', models.CharField(max_length=50)),
                ('post_subtitle', models.CharField(max_length=100)),
                ('post_description', models.TextField(default='Descripcion')),
                ('post_image', models.ImageField(blank=True, default='static/post_default.png', null=True, upload_to='media')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_active', models.BooleanField(default=True)),
                ('post_category', models.ForeignKey(default='Sin categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel_principal.categorias_juegos')),
            ],
            options={
                'ordering': ('-post_date',),
            },
        ),
        migrations.CreateModel(
            name='comentarios_usuarios',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_author', models.CharField(max_length=50)),
                ('comment_text', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_related_post', models.ForeignKey(default='Sin comentarios', null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel_principal.posteos_usuarios')),
            ],
        ),
    ]
