# Generated by Django 4.0.6 on 2023-12-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios_usuarios',
            name='comment_text',
            field=models.TextField(default='Ingresa tu comentario'),
        ),
        migrations.AlterField(
            model_name='contacta_nos',
            name='contact_mail',
            field=models.CharField(default='Ingresa tu correo', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacta_nos',
            name='contact_name',
            field=models.CharField(default='Ingresa tu nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacta_nos',
            name='contact_question',
            field=models.TextField(default='Ingresa tu consulta'),
        ),
        migrations.AlterField(
            model_name='posteos_usuarios',
            name='post_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel_principal.categorias_juegos'),
        ),
        migrations.AlterField(
            model_name='posteos_usuarios',
            name='post_description',
            field=models.TextField(default='Ingresa la descripcion larga del articulo'),
        ),
        migrations.AlterField(
            model_name='posteos_usuarios',
            name='post_subtitle',
            field=models.CharField(default='Descripcion corta del articulo', max_length=100),
        ),
        migrations.AlterField(
            model_name='posteos_usuarios',
            name='post_title',
            field=models.CharField(default='Titulo del articulo', max_length=50),
        ),
    ]
