# Generated by Django 4.0.6 on 2023-12-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_principal', '0005_alter_posteos_usuarios_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos_usuarios',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
